# Generated by Django 4.2.17 on 2025-04-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_staff_boarding_house_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearance',
            name='semester',
            field=models.CharField(choices=[('1ST_MID', '1st Sem - Midterm'), ('1ST_FIN', '1st Sem - Final'), ('2ND_MID', '2nd Sem - Midterm'), ('2ND_FIN', '2nd Sem - Final'), ('SUM', 'Summer')], max_length=7),
        ),
        migrations.AlterField(
            model_name='clearancerequest',
            name='semester',
            field=models.CharField(choices=[('1ST_MID', '1st Sem - Midterm'), ('1ST_FIN', '1st Sem - Final'), ('2ND_MID', '2nd Sem - Midterm'), ('2ND_FIN', '2nd Sem - Final'), ('SUM', 'Summer')], max_length=7),
        ),
    ]
