# Generated by Django 5.2 on 2025-04-29 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_systemsettings'),
        ('core', '0004_alter_clearance_semester_and_more'),
    ]

    operations = [
    ]
