# Generated by Django 5.2 on 2025-04-29 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_merge_20240624_0001'),
        ('core', '0005_merge_20250430_0718'),
    ]

    operations = [
    ]
