# Generated by Django 5.2 on 2025-05-01 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_20250430_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dormitory_owner_no_boarders',
            field=models.BooleanField(default=False, help_text='Flag indicating this is a dormitory owner with no active boarders'),
        ),
    ]
