# Generated by Django 4.2.17 on 2025-04-10 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_pcsafe'),
    ]

    operations = [
        migrations.AddField(
            model_name='programchair',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
